In [2]:
import numpy as np

In [3]:
A = np.random.rand(3,4)

In [4]:
A

array([[0.25517366, 0.6675886 , 0.59973312, 0.68253391],
       [0.85224951, 0.47801846, 0.20239122, 0.72735957],
       [0.21359481, 0.69976675, 0.15874064, 0.96175173]])

In [5]:
B = np.random.rand(4)

In [6]:
B

array([0.6878905 , 0.22044704, 0.63719036, 0.60322888])

In [11]:
A[:,1]

array([0.6675886 , 0.47801846, 0.69976675])